projects:
  topicsmaster:
    schemaPath: amplify/backend/api/topicsmaster/build/schema.graphql
    includes:
      - src/graphql/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql/unused
        region: us-east-1
        apiId: null
        maxDepth: 1
extensions:
  amplify:
    version: 3
